version: '3'
services:
  auldfellas:
    build:
      context: ./auldfellas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  dodgygeezers:
    build:
      context: ./dodgygeezers
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
  girlsallowed:
    build:
      context: ./girlsallowed
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
