version: '3.6'
services:
  auldfellas:
    build: auldfellas
    environment:
      HOSTNAME: auldfellas
    depends_on:
      - broker

  girlsallowed:
    build: girlsallowed
    environment:
      HOSTNAME: girlsallowed
    depends_on:
      - broker

  dodgygeezers:
    build: dodgygeezers
    environment:
      HOSTNAME: dodgygeezers
    depends_on:
      - broker

  broker:
    build: broker
    ports:
      - 2550:2550
    environment:
      HOSTNAME: broker

  client:
    build: client
    environment:
      HOSTNAME: client
    depends_on:
      - broker
      - auldfellas
      - girlsallowed
      - dodgygeezers
   